### ISSUE TITLE
Code to extract C-junctions and T-junctions from SceneCity

### ISSUE THREAD

**Issue by ToddBear** [zhou13/shapeunity#8]
Hi, Zhou, thanks for your greate job！
Will you release the code to extract C-junctions and T-junctions from SceneCity dataset?

**Comment by zhou13** [comment]
The code is at https://drive.google.com/drive/folders/1ZviOGlkqi3q6QS_gnmxvo5ocMQ4JX7n2. You want to take a look at `genlabel.py`.

**Comment by ToddBear** [comment]
Can you provides more details about the datasets ?

**Comment by ToddBear** [comment]
Can you provides more details about how to produce the datasets ? It seems that we have to prodece the scenes by the "scenecity" addon before running the code "render_building.py". Can you please provides the codes to generate the scenes for render. I really appreciate your help !

**Comment by zhou13** [comment]
Since I am no longer in academics, I don't have the bandwidth to provide a reproducible instruction on how to process the data, which has been further complicated due to the upgrade of the blender. However, all the code and material is already on  https://drive.google.com/drive/u/3/folders/13zE_7tL5ms7YagaXJbzLFTM1ygBv2jRS. You should be able to render the wireframe using the files in https://drive.google.com/drive/folders/1_B0dWo746_ua0QdNfJ16GiLEtdCEeGBr?usp=sharing with reasonable effort if you are familiar with blender and its scripting system.

**Comment by ToddBear** [comment]
I really appreciate you help and kindess. I found the scipts to generate a random scene when i open one of the blender project that you provided. This is of great help to me. Thank you again for you time on this matter.
